### PR TITLE
ComponentList Cleanup and Filtering + Client Upgrade

### PR DESCRIPTION
**Pull request by dOrgJelli**
Blocked by these issues:
https://github.com/daostack/client/pull/233
https://github.com/daostack/client/issues/234
https://github.com/daostack/client/pull/235

### CODE REVIEW

**Comment by shivgupt** [comment]
Looks great @dOrgJelli 
Thanks for cleaning up my messy filter and sort addition!

Not merging it yet coz I see build error from daostack client library.

**Comment by dOrgJelli** [comment]
Still waiting on a response @shivgupt, I tried a work around that was unsuccessful. Really what we need is a guarantee that EntityClasses can be constructed synchronously with the only requirement being the user provides a valid ID.

**Comment by dOrgJelli** [comment]
The proposed fix talked about here https://github.com/daostack/client/issues/234 has Jelle's sign off, but the work still needs to be done. This PR needs that work.

**Comment by dOrgJelli** [comment]
I've created a work around using the `async initialize` method in Component.tsx & Proposal.tsx.

**Comment by dOrgJelli** [comment]
@shivgupt the NPM package has been updated.

**Pull request merged**
